### ISSUE TITLE
NullPointerException at netbeanstypescript.TSService.updateFile

### ISSUE THREAD

**Issue by tzezula** [Everlaw/nbts#54] opened 2016-06-22 07:29 UTC
Reported by an exception reporter as https://netbeans.org/bugzilla/show_bug.cgi?id=262524

**Comment by jeffrey-easyesi** [comment] 2016-07-11 18:36
Duplicate of https://github.com/Everlaw/nbts/issues/52

**Comment by jeffrey-easyesi** [comment] 2016-07-13 22:27
Fixed in release 1.8.10.2

**Closed by jeffrey-easyesi** 2016-07-13 22:27 UTC
Labels: duplicate
