### ISSUE TITLE
Provide options for auto format / align rules with VSCode

### ISSUE THREAD

**Issue by simdevmon** [Everlaw/nbts#127] opened 2017-11-22 09:19 UTC
It would be nice if I could configure rules for auto formatting. 

For example imports are formatted like this
`import {Component, OnInit} from '@angular/core';`

An option to have whitespaces like the default formatting in Visual Studio Code would be good, that the same formatting rules can be applied across different IDEs.
`import { Component, OnInit } from '@angular/core';`

**Comment by Chris2011** [comment] 2017-11-23 10:12
This is a duplicate of: #74 and #81. Thx.

**Closed** 2019-02-06 07:51 UTC
