### ISSUE TITLE
Navigate (goto declaration) does not work after NetBeans restart

### ISSUE THREAD

**Issue by codecoster** [Everlaw/nbts#56] opened 2016-07-09 19:18 UTC
Using NetBeans IDE, Version Dev (Build 201607090002), I have problems with the goto-declaration feature of the plugin (nbts Version 1.8.10.1, probably related to #47)
Steps to reproduce:

- Clone the repo [https://github.com/codecoster/nbts-56](url)
- Go into the directory an `npm install && npm run start`
- After you get the notification "build success", you can cancel the `start` process
- Now you open NetBeans and _Open Project_, where you choose the nbts-56 project
- After opening, NetBeans will show a balloon-notification in which it encourages to review the automatic project-configuration, click into the notification
- Here, you set the 
 - _site root_ to the `dist` folder
 - _sources_ to the `src` folder
 - _selenium_ folder to the `e2e` folder
- Click Ok to complete the process

Now, when you open the src/app/app.component.ts file, you can jump for example into the '@angular/core' file as expected.
**However**, if you close NetBeans and then reopen it, this goto-declaration will not work anymore.

Closing and reopening the project won't help, and never got it to working again

Project is a simple angular-cli project (angular-cli: 1.0.0-beta.9)

**Comment by everflux** [comment] 2016-07-10 08:46
I have the same problem. Hypothesis: Related to source folders in NetBeans project?
Is there anything I can provide to help triage the cause? (I checked NetBeans messages.log, nothing that is immediately obvious as a problem)

**Comment by markiewb** [comment] 2016-07-10 18:51
@mark-everlaw: Check the position attribute of your hyperlinkext in the layer.xml. Perhaps your implementation has not the priority anymore?

**Comment by jeffrey-easyesi** [comment] 2016-07-11 18:35
You can't jump to files in `../node_modules` because they're outside of the source root so the Java side of the plugin is unaware of them.

**Comment by everflux** [comment] 2016-07-13 08:18
But it works correctly until a NetBeans restart. Is that due to having the project as a source root lingering around from the initial import?
I have opened this improvement request, would that fix the problem? https://netbeans.org/bugzilla/show_bug.cgi?id=262747
Please vote for it, if it would help :)

**Comment by jeffrey-easyesi** [comment] 2016-07-13 22:29
Fixed in release 1.8.10.2, you can now jump to things defined outside the project just like you can jump to things defined in lib.d.ts.

**Closed** 2016-07-20 05:48 UTC
