### ISSUE TITLE
tsconfig.json not found in Java EE project directory structure

### ISSUE THREAD

**Issue by OndraZizka** [Everlaw/nbts#43] opened 2016-03-29 23:45 UTC
In `/tsconfig.json`, I have

    {
      "compilerOptions": {
         "experimentalDecorators": true,

but I'm still getting the error "Experimental support for decorators is a feature ... " etc.

I haven't found other place to put this option to, hence filling this as it seems not to work.

**Comment by jeffrey-easyesi** [comment] 2016-03-29 23:55
It works for me. Two things to check:
1. Make sure `tsconfig.json` is valid - try compiling your project from the command line with `tsc`
2. Make sure `tsconfig.json` is somewhere where the NetBeans indexer can find it. If you're not sure, try creating a .ts file in the same directory, and opening it - if the plugin reports an "unknown source root" error, that directory isn't indexed.

**Comment by jsight** [comment] 2016-03-30 04:46
I suspect that this is related: https://github.com/Everlaw/nbts/issues/21

I think that it isn't finding the tsconfig.json file in the project root.

**Comment by OndraZizka** [comment] 2016-03-30 14:01
This is the structure of the project. It's a Java EE app. The `tsconfig.json` is at root, at src/main/webapp/ , at src/main/webapp/app with the main.js. Still not working (tried closing and opening the project). The compiler works fine. The file is visible in NetBeans Projects pane.

Can I get some debug log of the plugin to see where is it looking for the file? Also, how does it concat the paths? I have relative paths in rootDir, sourceRoot etc. Which ones do affect the plugin?

Sorry for using an issue to discuss, I promise I'll post it to stackoverflow if we resolve it :)

├── nbactions.xml
├── nb-configuration.xml
├── node_modules
│   ├── angular2
│   ├── ...
├── package.json
├── pom.xml
├── src
│   ├── main
        ├── java ...
        ├── resources
        └── webapp
            ├── app
            │   ├── components
            │   ├── constants.ts
            │   ├── main.ts
            │   ├── models
            │   ├── services
            │   └── templates
            ├── index.html
            ├── tsconfig.json
            └── WEB-INF ...
│   └── test
├── target
│   ├── ...
│   ├── windup-web
├── tsconfig.json
├── typings
│   └── ...
└── typings.json

**Comment by OndraZizka** [comment] 2016-03-30 14:18
I have put the `tsconfig.json` into `src/main/webapp` AND put the `node_modules` there too.  That works.

Could you please make the plugin look into the root dir of the project? IMHO it's the most logical place to check.

**Comment by jeffrey-easyesi** [comment] 2016-05-12 01:01
Duplicate of #21

**Closed by jeffrey-easyesi** 2016-05-12 01:01 UTC
Labels: duplicate
